### ISSUE TITLE
Getting fatal error.

### ISSUE THREAD

**Issue by aktur** [aormsby/Fork-Sync-With-Upstream-action#10]
My actions script fails with the following message:

fatal: refusing to merge unrelated histories
Error: The process '/bin/sh' failed with exit code 128

My forked project is:

https://github.com/aktur/docker-openvpn

**Comment by dskvr** [comment]
Same issue

**Comment by aormsby** [comment]
@aktur Right, I'd expect this in your case. You’ve made new commits to your branch that's tracking the upstream repo’s branch, which places you ahead of the upstream in your branch history. Even though there are no new commits to pull in from upstream, the `—ff-only` option doesn’t like this situation because it thinks you have a divergent history and won’t do a no-merge branch integration. (A nice resource to explain [—ff-only](https://blog.sffc.xyz/post/185195398930/why-you-should-use-git-pull-ff-only) if it helps.)

This sync action isn’t really meant to handle the case of working on the same branch you’re updating. Its intended use is updating an **unmodified** branch. Then it’s up to you to merge from the synced branch into whatever your working branch is. A more compatible workflow would be something like this —

![](https://www.adamormsby.com/posts/hugo-themes-making-modifications/cover.jpg)
_keep auto-syncing on 'master', do your customizations on 'working', merge from 'master' into 'working' as you see fit_

In this scenario, your local branch should never be ahead of the upstream branch, because it's not your workspace. And then you’d never get this failure.

@dskvr I suspect you have the same issue, but I'm unable to check your repo. Please let me know if you have a different issue.

Thanks for asking about this. If you feel like this should be explained more clearly in the README, please let me know your ideas and I’ll consider making an update. :)
