### ISSUE TITLE
action failed: [remote rejected]

### ISSUE THREAD

**Issue by paulGHub** [aormsby/Fork-Sync-With-Upstream-action#12]
my workflow: https://github.com/paulGHub/Python/actions/runs/328147668/workflow
maybe a silly question, but my action failed with the following error:

```
 ! [remote rejected] autoUptodate -> autoUptodate (refusing to allow a GitHub App to create or update workflow `.github/workflows/project_euler.yml` without `workflows` permission)
```

My secret token have full permission, confused to have this error.

**Comment by aormsby** [comment]
I *think* what's happening is that your secret token just doesn't have the permissions to update workflow files. Try checking the settings on your token.

Quick link - https://github.com/settings/tokens

Find this:
![Screen Shot 2020-10-26 at 02 04 54](https://user-images.githubusercontent.com/1312251/97142922-a7bcc480-172f-11eb-8a68-1083ffe09ade.png)

Try enabling that permission, and let me know what happens.

**Comment by paulGHub** [comment]
@aormsby ,Thanks for reply. To prevent similar problems, my token is set to have full permission. you can see:

![image](https://user-images.githubusercontent.com/46396534/97144566-a75c1200-179f-11eb-98a9-63b0cc290079.png)

that's what confusing me.

**Comment by aormsby** [comment]
Hmm... yes, I'm not totally sure, either. However, I did see that you're adding the secret to the sync step of your workflow _after_ the checkout step, and I'm wondering if you just have some odd credentials mixup because of that. I know that checkout persists credentials by default, so whatever you start with (not your secret, in this case) might carry on and conflict.

Maybe try a few of these things and see if any make a difference:

1. Use your secret in the initial checkout step instead. (I feel like this could do it.)
2. Disable persisting credentials during checkout --

```yaml
- uses: actions/checkout@v2
      with:
        persist-credentials: false
```
3. Make a fresh access token and try that out.

I really don't think it's an issue with the action, so I'm not sure there's much other help I can offer.

**Comment by paulGHub** [comment]
yes, i removed 
```
github_token: ${{ secrets.UPTODATE }}
```
part in **sync step** and in **checkout step** add
```
token: ${{ secrets.UPTODATE }}
```
it finally works through. THANKS~
