### ISSUE TITLE
Can't seem to figure out why it's pulling unnecessary commits that are already in the repo

### ISSUE THREAD

**Issue by Fernthedev** [aormsby/Fork-Sync-With-Upstream-action#14]
I've been trying to make my downstream fork of a project regularly pull and merge an upstream. I've done everything right (I believe anyways) and I am able to do it manually on my local machine.
However using this action doesn't seem to work as for some inexplicable reason it's basically trying to reset my branch to the upstream branch rather than pull.

This is the repo https://github.com/Fernthedev/taskcafe/runs/1576642715?check_suite_focus=true

Following the steps to merge it manually on my local machine works with flying colors so I'm not sure why this is showing such bizarre effects.

Even running the git log command the action uses to visualize the new commits that will be added doesn't do this. 

I would gladly appreciate any help to solve this issue :)

**Comment by aormsby** [comment]
Duplicate of #10 

> fatal: refusing to merge unrelated histories

So this is your issue. I designed this action to update an *untouched* branch with any upstream commits, and *untouched* is the key piece here. In a production environment, it's generally considered bad practice to make automatic merges to any branch from an external repo without reviewing what has changed and how it affects your codebase, so the tool won't do that. It needs a clean branch

I intended the action to be used in a dual-branch style workflow. Something like this --

![image](https://user-images.githubusercontent.com/1312251/102660901-7665e100-4141-11eb-9c3e-8860d1244d7a.png)

Obviously, you'd have different branch names, but the idea is 'master' is your untouched branch. You don't develop on 'master', but it cleanly pulls updates from upstream regularly so you can do things like test new features or branch off and make nice PRs for the upstream repo.

The 'working' branch is where you do all your work, make all your changes, and build your product. As desired, you can review, merge, cherry-pick, etc. from 'master' into 'working' with all the power that a clean git branch provides. And you won't blow up your build by having an automatic tool smash your commits.

*However,* if you're feeling dangerous, you can always try to add options to the `git_pull_args` input for your git pull command to force a merge. Up to you.

I will say you aren't the first person to get confused by what the action does and doesn't do, so I may update the README to be more clear.

**Comment by Fernthedev** [comment]
Ah I see. I was trying to make a customized fork of a product while keeping upstream changes merging until something such as a merge conflict appears. Then I'd manually review and edit it. Basically something like the PaperMC team does with Paper (they pull upstream changes automatically, and any conflicts or bugs are fixed manually)

Very well then, thank you for clarifying.

**Comment by aormsby** [comment]
Yeah, I see what you're saying. I am wondering if modifying the `git_pull_args` input would work for you here. But there might be 2 issues at play.

First is that you're merging a ton of commits since your history diverged, so a conflict is pretty likely.
Second is this part of your log:

```text
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only
```
`git_pull_args` is just `git pull` by default, so by specifying your pull preferences (which would include your merge options), this second issue would go away, AND you might be able to go through with the process.

So maybe it's possible to do what you want. I just haven't tested it. It's worth a shot.

On my end, this tells me I probably need to set a pull config default in the action to avoid ambiguity in the git actions.

**Comment by aormsby** [comment]
Try `git_pull_args: '--ff --no-edit'`. If that doesn't work, you probably have a merge conflict.

I will make a note to run some tests this weekend. If it's not too dramatic a change, supporting your workflow might be good.

**Comment by Fernthedev** [comment]
I just tried your arguments and they don't seem to work. Weirdly though is that there should be no merge conflicts (and there aren't when I run it manually on my local machine) between upstream and origin. I have rebased origin/master onto upstream/master to make sure.

This is the current result: https://github.com/Fernthedev/taskcafe/runs/1579520914?check_suite_focus=true

You could also look through the multiple commits and runs I've attempted though I don't think you will since it's tedious and probably useless anyways.

P.S: I appreciate you looking into my use case and helping me out :)

**Comment by aormsby** [comment]
Do me a favor? Try simply `git_pull_args: '--no-edit'`. If there are no conflicts, this *should* merge everything without any trouble. It worked on a simple test repo I made, but I can't say for sure if it will work for your repo. Let me know what you get.

**Comment by aormsby** [comment]
Okay, I know what you can do.

Somewhat recently (not sure when, exactly), git was updated to prevent any kind of merge where the merging branches don't share a common history (i.e. divergent branches). So they added the option `--allow-unrelated-histories` to account for this. 

Based on what I know, **you can set `git_pull_args: '--allow-unrelated-histories'`** to do a merge between your branches.

I did try this, and it works as long as you have no conflicts. Unfortunately, even simple changes can be considered conflicts, so I'm not sure how far it will get you. Also, using this unrelated histories option is not at all recommended, so please be aware of the potential consequences.

Some reading:
- [some blog post](https://careerkarma.com/blog/error-git-refusing-to-merge-unrelated-histories/)
- [git docs](https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---allow-unrelated-histories)

Another option is something like `git_pull_args: '-s recursive -Xtheirs'` (or 'Xours') to select one side of the conflict over another. I don't really recommend this method either since you'd lose data, of course.

More reading:
- [stack overflow](https://stackoverflow.com/questions/2268172/git-merge-recursive-theirs-how-does-it-work)
- [git docs again](https://git-scm.com/docs/git-pull#Documentation/git-pull.txt--sltstrategygt)

That's about the best I can do for you. I don't know of any other way to approach an auto-merge, unfortunately. Hopefully, this info helps you out.

**PS:** I did make some other general improvements, including a fix for the message about pull config. I'll push a new version in a bit. Cheers. :)
