### ISSUE TITLE
has_new_commits erroneously evaluates to true

### ISSUE THREAD

**Issue by misaacs21** [aormsby/Fork-Sync-With-Upstream-action#21]
```
* branch            main       -> FETCH_HEAD
 * [new branch]      main       -> upstream/main
No new commits to sync, exiting
```

Despite this being the output of the Fork-Sync step, it still proceeded to run echo "There were new commits" (as per the example) and subsequent steps that relied on the if-statement being false.

**Comment by aormsby** [comment]
Is it your first time running the sync action? I think it always logs 'new' commits the first time because it doesn't have a has stored from previous runs. Should probably bug that.

**Comment by ahunt** [comment]
I'm seeing the same issue, after running the action multiple times without any changes on my fork or upstream (example here: https://github.com/ahunt/git/runs/2265456482?check_suite_focus=true ).

In fact I added an extra step:
```
printf "_%s_\n" ${{ steps.sync.outputs.has_new_commits }}
```
Which is printing "_false_".

In other words: it looks like this action is doing the right thing, but workflows are interpreting the string "false" as boolean true.

So I decided to write a separate workflow just to test bool values, and it does look like workflows is indeed consistently evaluating false as true:
Workflow (ignore the action.yml, I ended up not using that) : https://github.com/ahunt/actions-test/commit/552baf4fb28e43a7a8d1450bab81166e331dc448
Results: https://github.com/ahunt/actions-test/runs/2268355324?check_suite_focus=true
We would expect result-set-out (and result-set-env) to NOT be run, but they do run... and in both cases they confirm that the variable is indeed "false".

I've prepared PR #25 to propose simply NOT setting the false value, as that achieves the expected result with least hassle. I'm also planning to file an issue against Actions itself, because this behaviour seems wrong - but I'm not quite sure where to file it yet.

**Comment by aormsby** [comment]
It does sound like an Action issue, but I'm working on an update to the action so I can at least modify it to make sure it works for our purposes. Do you know if the same behavior is still occurring?

**Comment by aormsby** [comment]
The reason for this problem - at least in my sample workflow - is that I didn't use the correct syntax to check for outputs. The script works fine. The workflow condition does not.

Here's a fix:

```yaml
 - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
 - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
```

'==' and quotes around the values does the trick for me

**Comment by aormsby** [comment]
README updated to explain the troublesome syntax in both 2.4 and 3.0 🙂
