### ISSUE TITLE
Feature: GPG signing with action commits

### ISSUE THREAD

**Issue by glexiasvc** [aormsby/Fork-Sync-With-Upstream-action#33]
https://github.com/aormsby/Fork-Sync-With-Upstream-action/wiki/Scenarios-for-Advanced-Input

git_pull_args: is not valid anymore. I would submit a correction but unsure which of the _args is the current one and don't want to create more work.

Also, is there a way to specify a secret that contains a PGP key for checking to show the commit as verified?

**Comment by aormsby** [comment]
Ha! Not as simple as I thought. I didn't realize GPG signing in Actions was such a challenge for so many devs, but I've learned a few things today.

Right now, I don't think that supporting GPG setup during the sync makes a whole lot of sense, because the requirements there are sort of beyond the scope of the action. Instead, I think adding a GPG config step to the workflow before the sync would work better overall.

There's an action called [Import GPG](https://github.com/marketplace/actions/import-gpg) that [other users find effective](https://github.com/actions/runner/issues/667#issuecomment-775277257) for this task, and I'm going to try it out with my syn action. Maybe some minor adjustments are needed to avoid git config conflicts. If it works, this will be what I recommend for you as well.

**Comment by aormsby** [comment]
Yep, this is working for me with very small changes. @glexiasvc  I'd love if you would try it out - instructions in PR #35

**Comment by mbwmbw1337** [comment]
Confirmed fixed. Thank you! The issue is able to be resolved.

**Comment by glexiasvc** [comment]
Thank you again, @aormsby

**Comment by aormsby** [comment]
Merged and release as v3.1 👍
