### ISSUE TITLE
sync failing on live run but tests pass

### ISSUE THREAD

**Issue by tpletcher** [aormsby/Fork-Sync-With-Upstream-action#34]
Hi Folks,

Set up the sync action on a freshly forked repo, used your example yaml and ran in test mode with everything green. However, when I flip over to live mode, the sync is failing with this error (Full job run logs are attached):

---------------------
Syncing new commits...
272
From https://github.com/fcsonline/drill
273
 * branch            master     -> FETCH_HEAD
274
fatal: refusing to merge unrelated histories
275
ERROR:  exit 128
276
New commits could not be pulled.
277
Try running in test mode to verify your action input. If that does not help, please open an issue.
278
Resetting git config to previous settings.
279
Reset Complete
280

281
Error: The process '/usr/bin/sh' failed with exit code 128
-----------------------------

[1_Set up job.txt](https://github.com/aormsby/Fork-Sync-With-Upstream-action/files/7147559/1_Set.up.job.txt)
[2_Checkout target repo.txt](https://github.com/aormsby/Fork-Sync-With-Upstream-action/files/7147560/2_Checkout.target.repo.txt)
[3_Sync upstream changes.txt](https://github.com/aormsby/Fork-Sync-With-Upstream-action/files/7147561/3_Sync.upstream.changes.txt)
[12_Post Checkout target repo.txt](https://github.com/aormsby/Fork-Sync-With-Upstream-action/files/7147562/12_Post.Checkout.target.repo.txt)
[13_Complete job.txt](https://github.com/aormsby/Fork-Sync-With-Upstream-action/files/7147563/13_Complete.job.txt)

**Comment by aormsby** [comment]
I looked at your output, and I'm a little confused about what you're trying to accomplish. Let's try and sort this out.

1. You forked the fsconline/drill repo.
    Question - If you just forked the repo, please confirm that your fork contains all commits from the upstream repo.
2. You ran the action on your fork.
3.

**Comment by aormsby** [comment]
Hi @tpletcher, I took a look at all of your output, and I was able to recreate the problem. Your input is solid, and I think you've done everything correctly. I'm sure noticed that the generated list of new commits goes all the way back to that initial commit of the upstream repo.

Here's what's happening --
- You made your fork. Awesome.
- Then you added the .github/workflows/sync-action.yaml into your master branch, which added a commit to the master branch.
- When the action checks for new commits it compares the latest commit hash on both the target and the upstream repos. Since you added your workflow, these no longer match, and the action thinks _every_ commit in the repo is new. (It's a rather simplistic commit check).
- Technically speaking, git doesn't have a problem with that, but after your workflow commit you now have divergent histories on the master branch between the target and upstream repos, which is why you receive the git error `fatal: refusing to merge unrelated histories`.

Speaking frankly, this is a minor weakness of the sync action because it was designed to work on a branch that you don't make any commits on. However, you have some options to fix this --
1. Set => `upstream_pull_args: '--allow-unrelated-histories'` to allow the merge to continue as shown in the [wiki](https://github.com/aormsby/Fork-Sync-With-Upstream-action/wiki/Scenarios-for-Advanced-Input) (I even added more details based on your issue). This change _should_ also allow you to make your own commits to the master branch (but keep in mind you may need to add further input to manage merge conflicts). Adding this input would solve your problem immediately.
2. If you only intend to use this action for super simple syncs... honestly, you could just use the new built-in 'Fetch upstream' option that Github added to forked repos. The simplest solution is always the best solution, after all. Food for thought.

<img width="539" alt="Screen Shot 2021-09-18 at 2 27 31 PM" src="https://user-images.githubusercontent.com/1312251/133906372-b327a558-7e3f-40a6-ad52-5ec589843b0a.png">

I hope this helps, and I hope you can get beyond this roadblock. Please close this issue if either solution works for you. Happy coding!

**Comment by tpletcher** [comment]
Thanks! Makes sense. I'm really just looking to keep the fork sync'd to upstream so that "Fetch Upstream" should be fine. Appreciate the detailed response, have a great day.
