### ISSUE TITLE
Sync Public to Private

### ISSUE THREAD

**Issue by mbwmbw1337** [aormsby/Fork-Sync-With-Upstream-action#36]
I have a public github repo that I want to sync to my own private repo so my embarrassing code is not public.

What is the best way to make this happen? I initially "imported" the target upstream repo which worked, then set up the sync script; however, I kept getting errors related to unrelated histories.

I followed the steps and added `--allow-unrelated-histories `which worked but now every time the script runs it shows a merge operation even if no files have been changed. I am not adding any new files at this point, I will create a fork off the private branch to make code changes then merge them back in.

Is there a command or flag to force the script to pull down the upstream branch the first time it runs as a fork so the histories are common?

Steps to repeat:
1. Find target upstream branch for example "https://github.com/ccxt/ccxt/"
2. Create private repo called "ccxt" on your account
3. Run the fork-sync-with-upstream-action script. Fails with unrelated histories.
4. Try adding `--allow-unrelated-histories` script runs but then shows a merge event every time the script runs regardless of if there are changes/new commits or not.

I am likely doing something wrong so any advice you have would be much appreciated.

**Comment by aormsby** [comment]
Okay yeah, I see it always thinks there are new commits in this situation. That's not great, especially with such a large history to traverse. I suspect what's happening is that after the first sync from upstream, a merge commit is created whose hash is not the same as the last commit hash you synced from upstream. That last commit hash is what the action uses to check if it needs to try and pull new stuff, and it's a pretty naive implementation.

I think what's needed to fix it is --
1. Store the last synced commit hash from upstream
2. On sync run, compare the upstream branch head hash with the stored hash (not the target branch head)
3. Update the stored commit hash if there was a sync

I'm really hoping that's all that's required, but I'm also wondering if that extra merge commit will complicate pulling in new changes. Not sure, I'll have to try it out.

**Comment by aormsby** [comment]
Good news - I do have a fix that checks for new commits a bit more intelligently.
Bad news - I'm not sure it really solves your problem.

I was lucky enough that some new commits were made to ccxt, and I ran the action again to see if it would correctly check for new commits (it did). Since there were new commits this time, it tried to merge new stuff again. Unfortunately, there were merge conflicts that I was unable to resolve automatically as well as a rejection pushing from a shallow clone. I wonder if you'll have similar issues.

You're welcome to try the changes in your workflow -- `uses: aormsby/Fork-Sync-With-Upstream-action@merge-check-fix`

If that doesn't work, I'm not sure what else to try at the moment. Will have to think on it.

**Comment by aormsby** [comment]
UPDATE: I made a much better fix in the branch `check-fix-2` (PR linked above). Works for me based on your notes. I would like for you to try this out on both the fresh ccxt 'fork' and then after you run with success to check for early exit. Should be good this time.

**Comment by mbwmbw1337** [comment]
Thank you! I will give this a go and let you know. Excellent support and work on this project!

**Comment by aormsby** [comment]
#38 merged, released as v3.2
