### ISSUE TITLE
fatal: error processing shallow info: 4

### ISSUE THREAD

**Issue by burner1024** [aormsby/Fork-Sync-With-Upstream-action#41]
Hi.
Just switched to 3.2 and this error [popped up](https://github.com/BGforgeNet/sfall/runs/4546506130?check_suite_focus=true).
More importantly, it's not registered as an error, GHA run is marked successful.

**Comment by mattborghi** [comment]
Quick fix for me: using `v3.1`.

**Comment by aormsby** [comment]
@burner1024 Did 3.1 work for you?

---

It's actually not strange to me that the action exits as a success because it probably doesn't account for whatever error you've run into. If the check for commits fails, the action (naively) assumes there are no commits to sync. Basically, it needs to be more robust in checking for errors when trying to get commits.

But I don't know if that's worth fixing yet. Instead, try something for me. In your workflow, add the input option `shallow_since: '3 years'` or something older than the commits you want to grab.

I can see that you've never had a successful run of the sync action (not successful with an actual sync, anyway), and I have a hunch it's because the action simply isn't fetching a deep enough history of your upstream branch. So I think adding `shallow-since` input might fix that for your first run.

After your first run, you can remove or change that input value since you will (presumably) be syncing more often.

**Comment by burner1024** [comment]
> It's actually not strange to me that the action exits as a success because it probably doesn't account for whatever error you've run into

Yes, not strange, just bad. Probably better stick `set -xeu -o pipefail` inside.

3.1 worked for me, and 3.2 with `shallow_since` seem to have [worked](https://github.com/BGforgeNet/sfall/runs/4838127822?check_suite_focus=true) too. Thanks.

**Comment by aormsby** [comment]
Well, an error and failure would not be desirable in the case of checking for new commits. If I schedule the sync action to run every week but don't commit anything in that week between syncs, I don't want the action to fail just because there's nothing to sync. It's fully aware there is nothing to sync, and that's _okay_.

In fact, it's even _great_ that the action can handle that situation because avoiding a total failure also allows other steps in a workflow to continue as expected. There's nothing inherently wrong with finding nothing new to sync, so the action is designed to be okay with that.

The real issue that you encountered is that the action doesn't always handle 'first run' scenarios well, particularly if you have a long commit history to sync (like in your case). But that's why `shallow_since` exists. And if you want to control whether or not a workflow continues after the sync, you can check the [output var `has_new_commits`](https://github.com/aormsby/Fork-Sync-With-Upstream-action/wiki/Configuration#output-variables) which was made for this purpose.

Until a better approach arises, I think this works just fine.

---
Also, to respond to your suggestion - those settings wouldn't really help in this case --
- `set -o pipefail`: not compliant with POSIX shell
- `set -e`: exits with error on any failure (undesirable, as stated)
- `set -x`: only shows the command that was run, nothing related to the error

**Comment by burner1024** [comment]
I never said the action should fail when there's no commits to sync.
I think it should fail when its commands fail, and you don't have a specific handler for that specific failure. And you're not going to have a handler for every kind of failure.
Silently swallowing errors is bad. I only noticed it didn't work by luck. That's the real issue. It will happen again, until every command's exit code is controlled.

**Comment by suntong** [comment]
Hi, 

Is the error `fatal: error processing shallow info: 4` means the following?

> If I schedule the sync action to run every week but don't commit anything in that week between syncs, I don't want the action to fail just because there's nothing to sync. It's fully aware there is nothing to sync, and that's _okay_.

I got that when trying to run the workflow manually to see how it behaves. 

Thanks
